import { 資料 } from "../index.ts";
import { MultilingualString } from "@dui/smartmultilingual";

// Property Schema for AI-friendly component properties
export interface PropertySchema {
  type: "string" | "number" | "boolean" | "object" | "array" | "function";
  description: string; // English description for AI
  required: boolean;
  default?: unknown;
  // 新增欄位
  options?: string[]; // For string type: available options
  min?: number; // For number type: minimum value
  max?: number; // For number type: maximum value
  pattern?: string; // For string type: regex pattern
  example?: unknown; // Example value for AI reference
}

// Sub-block configuration for composition mode
export interface 子方塊配置 {
  方塊ID: string;
  參數: Record<string, unknown>;
}

// Parameter mapping for composition mode
export interface 參數映射 {
  [對外參數名: string]: {
    映射到: string; // Path to internal parameter, e.g., "子方塊[0].參數.title"
  };
}

// Default values for cube model
const DEFAULT_VALUES = {
  名稱: { en: "Basic Cube", "zh-tw": "基礎方塊", vi: "Khối cơ bản" },
  描述: {
    en: "A basic UI component that can be used in various layouts",
    "zh-tw": "可在各種佈局中使用的基礎 UI 元件",
    vi: "Một thành phần UI cơ bản có thể được sử dụng trong các bố cục khác nhau",
  },
  售價: 0,
  標籤集: [] as string[],
  模式: "內建" as "內建" | "組合" | "AI",
  元件路徑: "",
  屬性定義: {} as Record<string, PropertySchema>,
  子方塊: [] as 子方塊配置[],
  對外參數: {} as 參數映射,
  程式碼: "",
  審核狀態: "pending" as "pending" | "approved" | "rejected",
  上架狀態: false,
};

export default class 方塊 extends 資料 {
  // Basic fields (following existing model pattern)
  public 名稱: MultilingualString;
  public 描述: MultilingualString;
  public 售價: number;

  // Mode-specific fields
  public 模式: "內建" | "組合" | "AI";

  // Built-in mode fields
  public 元件路徑: string; // Relative path, e.g., "ui/Button"
  public 屬性定義: Record<string, PropertySchema>; // Auto-generated by TypeScript compiler API

  // Composition mode fields
  public 子方塊: 子方塊配置[]; // Sub-block configurations
  public 對外參數: 參數映射; // Parameter mapping rules

  // AI mode fields
  public 程式碼: string; // AI-generated JSX code
  public 審核狀態: "pending" | "approved" | "rejected"; // Security audit status
  public 上架狀態: boolean; // Public availability

  public constructor(
    data: Record<string, unknown> = {},
    可刪除: boolean = true,
  ) {
    super(data, 可刪除);
    
    // Initialize basic fields
    this.名稱 = new MultilingualString(data?.名稱 as Record<string, string> | undefined ?? DEFAULT_VALUES.名稱);
    this.描述 = new MultilingualString(data?.描述 as Record<string, string> | undefined ?? DEFAULT_VALUES.描述);
    this.售價 = (data?.售價 as number) ?? DEFAULT_VALUES.售價;
    
    // Initialize mode-specific fields
    this.模式 = (data?.模式 as "內建" | "組合" | "AI") ?? DEFAULT_VALUES.模式;
    this.元件路徑 = (data?.元件路徑 as string) ?? DEFAULT_VALUES.元件路徑;
    this.屬性定義 = (data?.屬性定義 as Record<string, PropertySchema>) ?? DEFAULT_VALUES.屬性定義;
    this.子方塊 = (data?.子方塊 as 子方塊配置[]) ?? DEFAULT_VALUES.子方塊;
    this.對外參數 = (data?.對外參數 as 參數映射) ?? DEFAULT_VALUES.對外參數;
    this.程式碼 = (data?.程式碼 as string) ?? DEFAULT_VALUES.程式碼;
    this.審核狀態 = (data?.審核狀態 as "pending" | "approved" | "rejected") ?? DEFAULT_VALUES.審核狀態;
    this.上架狀態 = (data?.上架狀態 as boolean) ?? DEFAULT_VALUES.上架狀態;
  }

  public override toJSON(): Record<string, unknown> {
    return {
      ...super.toJSON(),
      名稱: this.名稱.toJSON(),
      描述: this.描述.toJSON(),
      售價: this.售價,
      模式: this.模式,
      元件路徑: this.元件路徑,
      屬性定義: this.屬性定義,
      子方塊: this.子方塊,
      對外參數: this.對外參數,
      程式碼: this.程式碼,
      審核狀態: this.審核狀態,
      上架狀態: this.上架狀態,
    };
  }

  // Validation methods
  public validateBuiltIn(): boolean {
    return this.模式 === "內建" && 
           this.元件路徑.length > 0 && 
           Object.keys(this.屬性定義).length > 0;
  }

  public validateComposition(): boolean {
    return this.模式 === "組合" && 
           this.子方塊.length > 0 && 
           Object.keys(this.對外參數).length > 0;
  }

  public validateAI(): boolean {
    return this.模式 === "AI" && 
           this.程式碼.length > 0;
  }

  public isValid(): boolean {
    switch (this.模式) {
      case "內建":
        return this.validateBuiltIn();
      case "組合":
        return this.validateComposition();
      case "AI":
        return this.validateAI();
      default:
        return false;
    }
  }
}
